Now, there is a CVE in this repo:The password hasher in contrib/auth/hashers.py in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to enumerate users via a timing attack involving login requests..
Now the following functions is the cause for the CVE:tests/auth_tests/test_hashers.py:test_bcrypt_harden_runtime()tests/auth_tests/test_hashers.py:test_check_password_calls_harden_runtime()tests/auth_tests/test_hashers.py:test_pbkdf2_harden_runtime()django/contrib/auth/hashers.py:check_password()django/contrib/auth/hashers.py:check_password()django/contrib/auth/hashers.py:harden_runtime()django/contrib/auth/hashers.py:verify()django/contrib/auth/hashers.py:verify().

Now, I have fixed the CVE in some way, but I need a unit test script to determine whether my fix is successful.
The unit test scripts should follow the logic of the CVE. If running the scripts can still exploit the CVE, the unit test fails; otherwise, it passes.

Now, please write a unit test script with the path as with the unit test script path as ACI_unit_test.py.
To be noted, if the unit test passes, "print('The ACI unit test is passed!!!')", otherwise "print('The ACI unit test is failed!!!')".

Furthermore, please write a shell script so I can use the shell script to auto-deploy the environment for the repo and to run the unit test script as "python ACI_unit_test.py". And name the shell script as ACI_unit_test.sh.
Before you write the shell script, please carefully review the repo's ReadMe about how to install and deploy the repo. You should notice the Python version the repo uses.
Your shell scripts are executed in the repo dir directly, so you do not need to cd into the repo dir.

P.S: Please do not leave a placeholder for the unit test, but realize the code!!!